# Understanding the Context

We are trying to understand car crashes in the city of Chicago and based on only the dataset findings, we are required to make recommendations to the office of the mayor of Chicago, on the steps to take that would lead to a reduction in car crashes. 

In [1]:
# We will first load an sql extension. 
# Notebook extensions are simple add-ons that extend the basic 
# functionality of the notebook environment. 
# This extension will allow us to run SQL code in our Notebook.
# ---
#
%load_ext sql

In [2]:
# We will then connect to an in memory SQLite database within colaboratory. 
# Something to note is that this in memory dataset will be deleted as 
# soon the dataset connection is lost, meaning when our connection to 
# the servers is disconnected then our database will cease to exist.
# ---
#  
%sql sqlite://

'Connected: @None'

In [8]:
import pandas as pd

traffic = pd.read_csv('traffic_accidents.csv', index_col=False)

%sql DROP TABLE if EXISTS traffic

%sql PERSIST traffic;

 * sqlite://
Done.
 * sqlite://


'Persisted traffic'

In [9]:
traffic.tail()

crash_unit_id     rd_no  ... mcs_out_of_service_i  hazmat_class
7247         749691  JC453715  ...                  NaN           NaN
7248         749681  JC453683  ...                  NaN           NaN
7249         749682  JC453683  ...                  NaN           NaN
7250         749683  JC453707  ...                  NaN           NaN
7251         749684  JC453707  ...                  NaN           NaN

[5 rows x 71 columns]

In [4]:
%%sql
SELECT * FROM traffic LIMIT 5;

 * sqlite://
Done.


[(0, 758369, 'JC469557', '2019-10-12T01:57:00', 1, 'DRIVER', None, 720366.0, None, 'DODGE', 'NITRO', 'IL', 2011.0, 'UNKNOWN', 'PASSENGER', 'UNKNOWN/NA', 'W', 'STRAIGHT AHEAD', None, None, 1.0, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 1, None, 'OTHER', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None),
 (1, 758356, 'JC469523', '2019-10-12T00:30:00', 1, 'DRIVER', None, 720356.0, None, 'VOLVO', 'XC90', 'IL', 2020.0, 'NONE', 'SPORT UTILITY VEHICLE (SUV)', 'PERSONAL', 'S', 'SLOW/STOP IN TRAFFIC', None, None, 1.0, None, None, None, None, None, None, 1, None, None, None, None, None, None, None, None, None, None, 'SIDE-RIGHT', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None),
 (2, 758357, 'JC469523', '2019-10-12T00:30:00', 2, 'DRIVER', None, 720355.0, None, 'UNKNOWN', 'UNKNOWN', None, None, 'UNKNOWN', 'PICKUP', 'UNKNOWN/NA', 'S', 'OTHER', None, None, 1.0, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 1, None, None, 'TOTAL (ALL AREAS)', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None),
 (3, 758329, 'JC469467', '2019-10-11T23:41:00', 1, 'DRIVER', 2.0, 720325.0, None, 'TOYOTA MOTOR COMPANY, LTD.', 'UNKNOWN', 'IL', 2015.0, 'NONE', 'PASSENGER', 'PERSONAL', 'E', 'PASSING/OVERTAKING', 1, None, 3.0, None, 'unknown', 'unknown', None, None, None, 1, 1, 1, 1, 1, None, None, None, None, None, None, 'REAR', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None),
 (4, 758330, 'JC469467', '2019-10-11T23:41:00', 2, 'DRIVER', None, 720334.0, None, 'SUBARU', 'FORESTER', 'IL', 2014.0, 'NONE', 'PASSENGER', 'PERSONAL', 'E', 'TURNING LEFT', None, None, 1.0, None, None, None, None, 1, 1, None, None, None, None, None, None, None, None, None, 1, None, 'FRONT', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)]

In [5]:
#  Display a list of 5 makes that had the highest number of crashes
%%sql
SELECT DISTINCT make 
FROM traffic
WHERE unit_no > 3 LIMIT 5

 * sqlite://
Done.


[('TOYOTA MOTOR COMPANY, LTD.',),
 ('CHEVROLET',),
 ('LINCOLN-CONTINENTAL',),
 ('KIA MOTORS CORP',),
 ('BUICK',)]

In [6]:
# 1. Most personal vehicles involved in crashes were travelling towards which direction? 

%%sql
SELECT travel_direction, MAX(unit_no)
FROM traffic
WHERE vehicle_use = 'PERSONAL'

 * sqlite://
Done.


[('S', 6)]

In [7]:
# 2. Most personal vehicles involved in crashes were travelling towards which direction

%%sql
SELECT travel_direction FROM traffic WHERE vehicle_use = 'personal' ;

 * sqlite://
Done.


[]

In [ ]:
# 3. How many passengers were involved in personal cars were in accidents?

%%sql
SELECT SUM(num_passengers) FROM traffic WHERE vehicle_use = 'PERSONAL';

 * sqlite://
Done.


[(1069.0,)]

In [ ]:
# 4. How many passengers were involved in accidents while travelling in personal Sport Utility vehicles

%%sql
SELECT SUM(num_passengers) 
FROM traffic 
WHERE vehicle_use = 'PERSONAL'
AND vehicle_type = 'SPORT UTILITY VEHICLE (SUV)';

 * sqlite://
Done.


[(153.0,)]

In [ ]:
# 5. Compute the total number of Mercedez-Benz vehicles involved in accidents while being parked.

%%sql 
SELECT COUNT(make) 
FROM traffic
WHERE make = 'MERCEDES-BENZ'
AND maneuver = 'PARKED';

 * sqlite://
Done.


[(16,)]

In [ ]:
# 6. Compute the total occupant count per vehicle count.
%%sql
SELECT SUM(occupant_cnt)
FROM traffic

 * sqlite://
Done.


[(7779.0,)]

In [ ]:
# 7. Sort the number of passengers in descending order by 
# travel direction taking into account travel direction. 
# Return travel direction and no. of passengers.

%%sql
SELECT num_passengers, travel_direction
FROM traffic
WHERE num_passengers IS NOT NULL
ORDER BY num_passengers DESC LIMIT 5;

 * sqlite://
Done.


[(11.0, 'S'), (10.0, 'E'), (9.0, 'S'), (8.0, 'E'), (7.0, 'SW')]

In [ ]:
# 8. Select top 5 vehicle models involved in the accident with no defect, 
# order them by make and show their manoeuvre. 

%%sql
SELECT model, maneuver
FROM traffic
WHERE vehicle_defect = 'NONE' 
ORDER BY make LIMIT 10;


 * sqlite://
Done.


[('(UNLISTED MANUFACTURER)', 'STRAIGHT AHEAD'),
 ('A & B TRAILER MFG. CO., INC., CROWN POINT, IN', 'SLOW/STOP IN TRAFFIC'),
 ('ACURA', 'STRAIGHT AHEAD'),
 ('ACURA', 'OTHER'),
 ('ACURA', 'PARKED'),
 ('ACURA', 'STRAIGHT AHEAD'),
 ('ACURA', 'STRAIGHT AHEAD'),
 ('ACURA', 'ENTERING TRAFFIC LANE FROM PARKING'),
 ('ACURA', 'LEAVING TRAFFIC LANE TO PARK'),
 ('ACURA', 'STRAIGHT AHEAD')]

In [ ]:
# 9. Which ridesharing vehicles in an accident had the most number of passengers? 
# Return model, and no of passengers.

%%sql
SELECT model, num_passengers
FROM traffic
WHERE vehicle_use = 'RIDESHARE SERVICE'
ORDER BY num_passengers DESC;

 * sqlite://
Done.


[('MKZ', 4.0),
 ('MALIBU (CHEVELLE)', 3.0),
 ('Prius', 3.0),
 ('COROLLA', 3.0),
 ('RX350', 2.0),
 ('Aveo', 2.0),
 ('CAMRY', 2.0),
 ('ROGUE', 2.0),
 ('Outlander', 2.0),
 ('C300', 2.0),
 ('PASSAT', 2.0),
 ('NISSAN MAXIMA', 2.0),
 ('COROLLA', 1.0),
 ('NISSAN ALTIMA', 1.0),
 ('ROGUE', 1.0),
 ('CIVIC', 1.0),
 ('COROLLA', 1.0),
 ('FUSION', 1.0),
 ('PASSAT', 1.0),
 ('CAMRY', 1.0),
 ('GENESIS', 1.0),
 ('CAMRY', 1.0),
 ('SONATA', 1.0),
 ('NISSAN ALTIMA', 1.0),
 ('Accent', 1.0),
 ('UNKNOWN', 1.0),
 ('JOURNEY', 1.0),
 ('FORTE', 1.0),
 ('Focus', 1.0),
 ('CAMRY', 1.0),
 ('Highlander(beginning vehicle year 2001)', 1.0),
 ('UNKNOWN', 1.0),
 ('UNKNOWN', 1.0),
 ('FIESTA', 1.0),
 ('JETTA', 1.0),
 ('FUSION', 1.0),
 ('CARAVAN', 1.0),
 ('MKZ', 1.0),
 ('SOUL', 1.0),
 ('ES300', 1.0),
 ('SONATA', 1.0),
 ('UNKNOWN', 1.0),
 ('MKT', 1.0),
 ('Prius', 1.0),
 ('UNKNOWN', 1.0),
 ('NISSAN ALTIMA', 1.0),
 ('ROGUE', None),
 ('CAMRY', None),
 ('MDX', None),
 ('JETTA', None),
 ('JETTA', None),
 ('NAVIGATOR', None),
 ('COROLLA', None),
 ('SORENTO', None),
 ('Prius', None),
 ('UNKNOWN', None),
 ('SENTRA (DATSUN AND NISSAN HAVE MERGED)', None),
 ('Focus', None),
 ('CAMRY', None),
 ('SENTRA (DATSUN AND NISSAN HAVE MERGED)', None),
 ('FORTE', None),
 ('ESCAPE (SUV)', None),
 ('ACURA', None),
 ('ELANTRA', None),
 ('FORTE', None),
 ('323', None),
 ('Prius', None),
 ('PASSAT', None),
 ('NISSAN ALTIMA', None),
 ('Prius', None),
 ('SENTRA (DATSUN AND NISSAN HAVE MERGED)', None),
 ('ROGUE', None),
 ('NISSAN ALTIMA', None),
 ('CRUZE', None),
 ('SENTRA (DATSUN AND NISSAN HAVE MERGED)', None),
 ('S90', None),
 ('FORD', None),
 ('TAHOE', None),
 ('ESCAPE (SUV)', None),
 ('TUCSON', None),
 ('UNKNOWN', None),
 ('Grand Cherokee (for vehicle years 1989 to present)', None),
 ('CRUZE', None),
 ('Prius', None),
 ('ACCORD', None),
 ('FORTE', None),
 ('CRV', None),
 ('NISSAN ALTIMA', None),
 ('Mazda 3', None),
 ('CAMRY', None),
 ('MALIBU (CHEVELLE)', None),
 ('Murano', None),
 ('SONATA', None),
 ('ELANTRA', None),
 ('GRAND MARQUIS', None),
 ('MKZ', None),
 ('SOUL', None)]

# Summary Of Findings

* From my analysis, the car make with the highest number of crashes is from TOYOTA MOTOR COMPANY, LTD.
* Most personal vehicles invilved in crashes were travelling to the South
* The total number of passengers involved in personal car accidents is 1069.0
* The total number of passengers travelling in personal Sports Utility vehicles is 153.0
* The total number of Mercedez-Benz vehicles involved in accidents while being parked is 16
* The the total occupant count per vehicle count is 7779.0
* The ridesharing service vehicle model with the most number of passengers involved in an accident is MKZ with a total number of 4 passengers

# Recommendations

* TOYOTA MOTOR COMPANY, LTD. should rigourosuly inspect perform vehicle performance in order to detect any defects which in turn greatly reduce the number of accidents caused by vehicle defects.
* All roads leadding to the south should be inspected for any hazards that may lead to road accidents.
* The ridesharing service providing its services with the vehicle model MKZ should dleve more into its policies which may help shed more light as to why they have the most number of passengers inveloved in accidents